"use strict"
const unions = [
    { FID: 1, offspring: 1, spouse: 2 },
    { FID: 2, offspring: 3, spouse: 4 },
    { FID: 3, offspring: 5, spouse: 6 },
    { FID: 4, offspring: 7, spouse: 8 },
    {},
    { FID: 6, offspring: 10, spouse: 11 },
    { FID: 7, offspring: 12, spouse: 13 },
    {},
    { FID: 9, offspring: 15, spouse: 16 },
    { FID: 10, offspring: 17, spouse: 18 },
    {},
    { FID: 12, offspring: 20, spouse: 21 },
    {},
    {},
    {},
    { FID: 16, offspring: 25, spouse: 26 },
    { FID: 17, offspring: 27, spouse: 28 },
    { FID: 18, offspring: 29, spouse: 30 },
    { FID: 19, offspring: 31, spouse: 32 },
    { FID: 20, offspring: 33, spouse: 34 },
    {},
    {},
    { FID: 23, offspring: 37, spouse: 38 },
    {},
    { FID: 25, offspring: 40, spouse: 41 },
    {},
    { FID: 27, offspring: 43, spouse: 44 },
    {},
    {},
    { FID: 30, offspring: 47, spouse: 48 },
    {},
    { FID: 32, offspring: 50, spouse: 51 },
    {},
    { FID: 34, offspring: 53, spouse: 54 },
    {},
    { FID: 36, offspring: 56, spouse: 57 },
    { FID: 37, offspring: 58, spouse: 59 },
    {},
    {},
    { FID: 40, offspring: 62, spouse: 63 },
    { FID: 41, offspring: 64, spouse: 65 },
    {},
    { FID: 43, offspring: 67, spouse: 68 },
    {},
    { FID: 45, offspring: 70, spouse: 71 },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    { FID: 57, offspring: 83, spouse: 84 },
    {},
    { FID: 59, offspring: 86, spouse: 87 },
    {},
    {},
    { FID: 62, offspring: 90, spouse: 91 },
    { FID: 63, offspring: 92, spouse: 93 },
    { FID: 64, offspring: 94, spouse: 95 },
    {},
    {},
    { FID: 67, offspring: 98, spouse: 99 },
    { FID: 68, offspring: 100, spouse: 101 },
    {},
    {},
    {},
    { FID: 72, offspring: 105, spouse: 106 },
    {},
    {},
    {},
    {},
    {},
    { FID: 78, offspring: 112, spouse: 113 },
    { FID: 79, offspring: 114, spouse: 115 },
    {},
    { FID: 81, offspring: 117, spouse: 118 },
    {},
    {},
    { FID: 84, offspring: 121, spouse: 122 },
    { FID: 85, offspring: 123, spouse: 124 },
    {},
    { FID: 87, offspring: 126, spouse: 127 },
    { FID: 88, offspring: 128, spouse: 129 },
    {},
    {},
    { FID: 91, offspring: 132, spouse: 133 },
    {},
    {},
    { FID: 94, offspring: 136, spouse: 137 },
    { FID: 95, offspring: 138, spouse: 139 },
    {},
    {},
    { FID: 98, offspring: 142, spouse: 143 },
    {},
    {},
    { FID: 101, offspring: 146, spouse: 147 },
    {},
    {},
    { FID: 104, offspring: 150, spouse: 151 },
    { FID: 105, offspring: 152, spouse: 153 },
    {},
    {},
    { FID: 108, offspring: 156, spouse: 157 },
    {},
    { FID: 110, offspring: 159, spouse: 160 },
    {},
    { FID: 112, offspring: 162, spouse: 163 },
    {},
    { FID: 114, offspring: 165, spouse: 166 },
    { FID: 115, offspring: 167, spouse: 168 },
    { FID: 116, offspring: 169, spouse: 170 },
    { FID: 117, offspring: 171, spouse: 172 },
    { FID: 118, offspring: 173, spouse: 174 },
    {},
    {},
    { FID: 121, offspring: 177, spouse: 178 },
    { FID: 122, offspring: 179, spouse: 180 },
    {},
    {},
    {},
    {},
    { FID: 127, offspring: 185, spouse: 186 },
    { FID: 128, offspring: 187, spouse: 188 },
    { FID: 129, offspring: 189, spouse: 190 },
    { FID: 130, offspring: 191, spouse: 192 },
    { FID: 131, offspring: 193, spouse: 194 },
    { FID: 132, offspring: 195, spouse: 196 },
    { FID: 133, offspring: 197, spouse: 198 },
    {},
    { FID: 135, offspring: 200, spouse: 201 },

]

const startID = 1

const individuals = [
    { ID: 1, FID: 0, gender: 'M', name: 'Raja Ram Talukdar' },
    { ID: 2, FID: -1, name: 'Wife', gender: 'F' },
    { ID: 3, FID: 1, name: 'Daughter', gender: 'F' },
    { ID: 4, FID: -1, name: 'Raja Rai Jiban', comment: 'Natore' },
    { ID: 5, FID: 1, gender: 'M', name: 'Bibhab Roy Talukdar' },
    { ID: 6, FID: -1, name: 'Wife', gender: 'F' },
    { ID: 7, FID: 3, name: 'Daughter', gender: 'F' },
    { ID: 8, FID: -1, gender: 'M', name: 'Shanti Roy Sanyal' },
    { ID: 9, FID: 3, gender: 'M', name: 'Swapan Roy Majumdar' },
    { ID: 10, FID: 3, gender: 'M', name: 'Krishna Kant Majumdar' },
    { ID: 11, FID: -1, name: 'Daughter of Nidhu Ram', gender: 'F' },
    { ID: 12, FID: 6, name: 'Daughter', gender: 'F' },
    { ID: 13, FID: -1, gender: 'M', name: 'Krishna Shankar Moitra' },
    { ID: 14, FID: 6, gender: 'M', name: 'Gopi Kanata Majumdar' },
    { ID: 15, FID: 6, name: 'Kamala Kant Majumdar', aka: 'Dukhu' },
    { ID: 16, FID: -1, name: 'Kali Sundari', gender: 'F' },
    { ID: 17, FID: 9, gender: 'M', name: 'Hari Narayan Majumdar' },
    { ID: 18, FID: -1, name: 'Wife', gender: 'F' },
    { ID: 19, FID: 10, gender: 'M', name: 'To Do' },
    { ID: 20, FID: 9, gender: 'M', name: 'Ram Narayan Majumdar' },
    { ID: 21, FID: -1, name: 'Hara Sundari, Swaraswati', gender: 'F' },
    { ID: 22, FID: 12, name: 'Daughter', gender: 'F' },
    { ID: 23, FID: 12, name: 'Daughter', gender: 'F' },
    { ID: 24, FID: 12, gender: 'M', name: 'Hara Nath Majumdar' },
    { ID: 25, FID: 12, gender: 'M', name: 'Uma Kant Majumdar' },
    { ID: 26, FID: -1, name: 'Uma Sundari', gender: 'F' },
    { ID: 27, FID: 16, gender: 'M', name: 'Rajani Kant Majumdar' },
    { ID: 28, FID: -1, name: 'Charulata', gender: 'F' },
    { ID: 29, FID: 17, gender: 'M', name: 'Sudhir Kumar Majumdar' },
    { ID: 30, FID: -1, name: 'Bimal Bala', gender: 'F' },
    { ID: 31, FID: 18, name: 'Uma Majumdar', gender: 'F', aka: 'Dulu' },
    { ID: 32, FID: -1, gender: 'M', name: 'Anil Kumar Choudhuri' },
    { ID: 33, FID: 19, name: 'Anshuman Choudhuri', aka: 'Bappa' },
    { ID: 34, FID: -1, name: 'Sampa', gender: 'F' },
    { ID: 35, FID: 20, gender: 'M', name: 'Arjun Choudhuri' },
    { ID: 36, FID: 20, name: 'Daughter', gender: 'F' },
    { ID: 37, FID: 18, name: 'Supriya Majumdar', aka: 'Manik' },
    { ID: 38, FID: -1, name: 'Saraswati', aka: 'Sana', gender: 'F' },
    { ID: 39, FID: 18, name: 'Satyabra Majumdar', aka: 'Kanai' },
    { ID: 40, FID: 18, name: 'Jayanti Majumdar', gender: 'F' },
    { ID: 41, FID: -1, name: 'Shyam Kumar Bagchi', aka: 'Shentu' },
    { ID: 42, FID: 25, name: 'Soma Bagchi', gender: 'F' },
    { ID: 43, FID: 18, name: 'Malabika Majumdar', gender: 'F', aka: 'Mala' },
    { ID: 44, FID: -1, gender: 'M', name: 'Swaranjan Sanyal' },
    { ID: 45, FID: 27, name: 'Daughter', aka: 'Munna', gender: 'F' },
    { ID: 46, FID: 27, name: 'Daughter', aka: 'Tinna', gender: 'F' },
    { ID: 47, FID: 18, name: 'Debabrata Majumdar', aka: 'Madhu' },
    { ID: 48, FID: -1, name: 'Dhruba Sanyal', gender: 'F' },
    { ID: 49, FID: 30, name: 'Deepayan Majumdar', aka: 'Deep' },
    { ID: 50, FID: 18, name: 'Arundhati Majumdar', aka: 'Buru', gender: 'F' },
    { ID: 51, FID: -1, gender: 'M', name: 'Debaprasad Moitra' },
    { ID: 52, FID: 32, name: 'Neelanjana Majumdar', gender: 'F', aka: 'Neela' },
    { ID: 53, FID: 18, name: 'Kamalesh Majumdar', aka: 'Montu,Gobindo' },
    { ID: 54, FID: -1, name: 'Chandra', gender: 'F' },
    { ID: 55, FID: 34, gender: 'M', name: 'Koushik Majumdar' },
    { ID: 56, FID: 17, gender: 'M', name: 'Sushil Kumar Majumdar' },
    { ID: 57, FID: -1, name: 'Hriday Bala', gender: 'F' },
    { ID: 58, FID: 36, name: 'Shankari Majumdar', gender: 'F' },
    { ID: 59, FID: -1, gender: 'M', name: 'Dibyendu Mukherjee' },
    { ID: 60, FID: 37, gender: 'M', name: 'Son' },
    { ID: 61, FID: 37, name: 'Daughter', gender: 'F' },
    { ID: 62, FID: 17, gender: 'M', name: 'Subodh Kumar Majumdar' },
    { ID: 63, FID: -1, name: 'Anna Dorothi', gender: 'F' },
    { ID: 64, FID: 40, gender: 'M', name: 'Orun Majumdar' },
    { ID: 65, FID: -1, name: 'Neelima', gender: 'F' },
    { ID: 66, FID: 41, gender: 'M', name: 'Marcus Majumdar' },
    { ID: 67, FID: 40, name: 'Meera Majumdar', gender: 'F' },
    { ID: 68, FID: -1, gender: 'M', name: 'Dr Ulrich' },
    { ID: 69, FID: 43, gender: 'M', name: 'Rabindra' },
    { ID: 70, FID: 17, name: 'Sabitri Majumdar', gender: 'F' },
    { ID: 71, FID: -1, gender: 'M', name: 'Kumud Ghatak' },
    { ID: 72, FID: 45, name: 'Saroj Bandhu Ghatak', aka: 'Gopal' },
    { ID: 73, FID: 45, name: 'Nikhil Bandu Ghatak', aka: 'Kani' },
    { ID: 74, FID: 45, name: 'Pran Bandhu Ghatak', aka: 'Panu' },
    { ID: 75, FID: 45, gender: 'M', name: 'Nishu? Ghatak' },
    { ID: 76, FID: 45, gender: 'M', name: 'Bulu? Ghatak' },
    { ID: 77, FID: 45, name: 'Rajlakshmi Ghatak', gender: 'F' },
    { ID: 78, FID: 45, gender: 'M', name: 'Neemu? Ghatak' },
    { ID: 79, FID: 45, gender: 'M', name: 'Shanti? Ghatak' },
    { ID: 80, FID: 45, gender: 'M', name: 'Anima? Ghatak' },
    { ID: 81, FID: 45, name: 'Hasi? Ghatak', gender: 'F' },
    { ID: 82, FID: 17, name: 'Sati Majumdar', gender: 'F', comment: 'died_when_one_year_old' },
    { ID: 83, FID: 17, name: 'Haridasi Majumdar', gender: 'F' },
    { ID: 84, FID: -1, gender: 'M', name: 'Shri Roy' },
    { ID: 85, FID: 57, gender: 'M', name: 'Bhabani Roy' },
    { ID: 86, FID: 57, gender: 'M', name: 'Badal Roy' },
    { ID: 87, FID: -1, name: 'Tapati', gender: 'F' },
    { ID: 88, FID: 59, gender: 'M', name: 'Annirudhha Roy' },
    { ID: 89, FID: 57, gender: 'M', name: 'Chandi? Roy' },
    { ID: 90, FID: 57, gender: 'M', name: 'Gopal Roy' },
    { ID: 91, FID: -1, name: 'Wife', gender: 'F' },
    { ID: 92, FID: 57, gender: 'M', name: 'Bhaybol? Roy' },
    { ID: 93, FID: -1, name: 'Sandhya', gender: 'F' },
    { ID: 94, FID: 57, name: 'Juthi? Roy', gender: 'F' },
    { ID: 95, FID: -1, gender: 'M', name: 'Husband' },
    { ID: 96, FID: 64, gender: 'M', name: 'Son' },
    { ID: 97, FID: 57, gender: 'M', name: 'Amal Roy' },
    { ID: 98, FID: 17, name: 'Kamala Majumdar', gender: 'F' },
    { ID: 99, FID: -1, gender: 'M', name: 'Radha Kant Goswami' },
    { ID: 100, FID: 67, name: 'Mihir Kumar Goswami', aka: 'Kalojam' },
    { ID: 101, FID: -1, name: 'Mimi?', aka: 'Mimi', gender: 'F' },
    { ID: 102, FID: 68, name: 'Omkar Goswami', aka: 'Bubun' },
    { ID: 103, FID: 68, name: 'Son', aka: 'Buchai' },
    { ID: 104, FID: 67, name: 'Manju Goswami', gender: 'F' },
    { ID: 105, FID: 67, name: 'Kajal Goswami', gender: 'F' },
    { ID: 106, FID: -1, gender: 'M', name: 'Shri Majumdar' },
    { ID: 107, FID: 72, name: 'Daughter', aka: 'Banhi', gender: 'F' },
    { ID: 108, FID: 72, name: 'Daughter', gender: 'F' },
    { ID: 109, FID: 67, gender: 'M', name: 'Mukul Goswami' },
    { ID: 110, FID: 67, name: 'Daughter', aka: 'Champa', gender: 'F' },
    { ID: 111, FID: 67, name: 'Daughter', aka: 'Dipu', gender: 'F' },
    { ID: 112, FID: 17, name: 'Sanat Kumar Majumdar', dob: '21-Apr-1911', aka: 'Botu' },
    { ID: 113, FID: -1, name: 'Parul Choudhuri', gender: 'F', dob: '31-Aug-1918' },
    { ID: 114, FID: 78, name: 'Rukmini Majumdar', gender: 'F', aka: 'Rumku', dob: '26-Jan-1944' },
    { ID: 115, FID: -1, gender: 'M', name: 'Dilip Bagchi' },
    { ID: 116, FID: 79, name: 'Parthasarathi Bagchi', dob: '4-Jul-1970', aka: 'Babla' },
    { ID: 117, FID: 79, name: 'Shubhadra Bagchi', dob: '20-Jan-1981', aka: 'Dola', gender: 'F' },
    { ID: 118, FID: -1, gender: 'M', name: 'Amit Chowdhury' },
    { ID: 119, FID: 81, name: 'Ananyaa Chowdhury', gender: 'F', aka: 'Buchi', dob: '4-Aug-2011' },
    { ID: 120, FID: 81, name: 'Arpita Chowdhury', gender: 'F', aka: 'Bubu', dob: '5-Apr-2018' },
    { ID: 121, FID: 78, name: 'Sudeshna Majumdar', gender: 'F', aka: 'Babli', dob: '18-Aug-1947' },
    { ID: 122, FID: -1, gender: 'M', name: 'Tarit Gupta' },
    { ID: 123, FID: 84, name: 'Aninidita Gupta', dob: '1-Apr-1971', gender: 'F', aka: 'Ruby' },
    { ID: 124, FID: -1, gender: 'M', name: 'Sugata Pratik Khastgir' },
    { ID: 125, FID: 85, name: 'Teerna Saugata Khastgir', gender: 'F', dob: '6-Jan-1998' },
    { ID: 126, FID: 78, name: 'Abhijit Majumdar', dob: '17-Mar-1951', aka: 'Bachchoo' },
    { ID: 127, FID: -1, name: 'Anunita Chakravarti', aka: 'Tota', gender: 'F', dob: '17-Jun-1960' },
    { ID: 128, FID: 87, name: 'Abhishek Majumdar', dob: '11-Apr-1985', aka: 'Jeet' },
    { ID: 129, FID: -1, name: 'Sarah Elliot', dob: '11-Nov-1984', gender: 'F' },
    { ID: 130, FID: 88, name: 'Henry Hrishik Majumdar', dob: '10-Oct-2015' },
    { ID: 131, FID: 88, name: 'George Aditya Majumdar', dob: '12-May-2018' },
    { ID: 132, FID: 87, name: 'Arjun Majumdar', dob: '25-Feb-1989', aka: 'Joy' },
    { ID: 133, FID: -1, name: 'Setarah Bamad Baker', aka: 'Seti', gender: 'F' },
    { ID: 134, FID: 17, gender: 'M', name: 'Shib Kumar Majumdar' },
    { ID: 135, FID: 17, gender: 'M', name: 'Shishir Kumar Majumdar' },
    { ID: 136, FID: 17, name: 'Annupurna Majumdar', gender: 'F' },
    { ID: 137, FID: -1, gender: 'M', name: 'Suresh Chakravarti' },
    { ID: 138, FID: 94, name: 'Shyamal Kanti Chakravarti', aka: 'Bablu' },
    { ID: 139, FID: -1, name: 'Basanti', gender: 'F' },
    { ID: 140, FID: 95, name: 'Daughter', aka: 'Minku', gender: 'F' },
    { ID: 141, FID: 95, name: 'Somdatta Chakravarti', aka: 'Takai', gender: 'F' },
    { ID: 142, FID: 94, name: 'Baijayanti Chakravarti', gender: 'F', aka: 'Khuku' },
    { ID: 143, FID: -1, gender: 'M', name: 'Shanti Bhushan Banerjee' },
    { ID: 144, FID: 98, name: 'Kaushik Banerjee', aka: 'Shinu' },
    { ID: 145, FID: 98, name: 'Son', aka: 'Kajuba' },
    { ID: 146, FID: 94, name: 'Somya Kanti Chakravarti', aka: 'Monglu' },
    { ID: 147, FID: -1, name: 'Krisha', gender: 'F' },
    { ID: 148, FID: 101, name: 'Soha Chakravarti', aka: 'Koni', gender: 'F' },
    { ID: 149, FID: 94, name: 'Enakshi Chakravari', gender: 'F', aka: 'Tutul' },
    { ID: 150, FID: 17, name: 'Gouri Majumdar', gender: 'F', dob: '1919' },
    { ID: 151, FID: -1, name: 'Sudhish Roy', dob: '1909' },
    { ID: 152, FID: 104, name: 'Sudhodhan Roy', aka: 'Ganesh', dob: '9-Feb-1942' },
    { ID: 153, FID: -1, name: 'Banani', gender: 'F' },
    { ID: 154, FID: 105, name: 'Shiddharta Roy', dob: '7-Nov-1974', aka: 'Gobi' },
    { ID: 155, FID: 105, name: 'Meenakshi Roy', aka: 'Mimi', gender: 'F', dob: '27-Jan-1982' },
    { ID: 156, FID: 104, name: 'Madhabi Roy', gender: 'F', aka: 'Manti' },
    { ID: 157, FID: -1, gender: 'M', name: 'Chtittaranjan Bhattacharya' },
    { ID: 158, FID: 108, name: 'Debika Bhattacharya', aka: 'Debi', gender: 'F' },
    { ID: 159, FID: 104, name: 'Basudeb Roy', dob: '1946' },
    { ID: 160, FID: -1, gender: 'M', name: 'Sumitra' },
    { ID: 161, FID: 110, name: 'Debjani Roy', gebder: 'F', aka: 'Rinku' },
    { ID: 162, FID: 104, name: 'Somdeb Roy', dob: 'Apr-1951', aka: 'Kutush' },
    { ID: 163, FID: -1, name: 'Chandita', gender: 'F', aka: 'Tulu' },
    { ID: 164, FID: 112, name: 'Shubra Roy', gender: 'F' },
    { ID: 165, FID: 16, name: 'Mrinalini Majumdar', gender: 'F' },
    { ID: 166, FID: -1, name: 'Haradas Achrya Choudhuri', comment: 'from_Muktagacha' },
    { ID: 167, FID: 16, gender: 'M', name: 'Kashi Kant Majumdar' },
    { ID: 168, FID: -1, name: 'Rai Kishori', gender: 'F' },
    { ID: 169, FID: 115, gender: 'M', name: 'Prafulla Kumar Majumdar' },
    { ID: 170, FID: -1, name: 'Gouri', gender: 'F' },
    { ID: 171, FID: 116, name: 'Son', aka: 'Tapan' },
    { ID: 172, FID: -1, name: 'Karabi', gender: 'F' },
    { ID: 173, FID: 116, gender: 'M', name: 'Son' },
    { ID: 174, FID: -1, name: 'Wife', gender: 'F' },
    { ID: 175, FID: 115, name: 'Amulya Kumar Majumdar', comment: 'missing_from_RSKM_note' },
    { ID: 176, FID: 115, name: 'Priya Kumar Majumdar', comment: 'missing_from_RSKM_note' },
    { ID: 177, FID: 115, name: 'Mahamaya Majumdar', gender: 'F' },
    { ID: 178, FID: -1, gender: 'M', name: 'Jitendra Moitra' },
    { ID: 179, FID: 115, name: 'Baidyanath Majumdar', comment: 'missing_from_RKM_Notebook' },
    { ID: 180, FID: -1, name: 'Leela', gender: 'F' },
    { ID: 181, FID: 122, gender: 'M', name: 'Shyamali Majumdar' },
    { ID: 182, FID: 122, gender: 'M', name: 'Ashok Majumdar' },
    { ID: 183, FID: 122, name: 'Son', aka: 'Jogu' },
    { ID: 184, FID: 122, name: 'Daughter', aka: 'Bani', gender: 'F' },
    { ID: 185, FID: 115, name: 'Jogmaya Majumdar', gender: 'F' },
    { ID: 186, FID: -1, gender: 'M', name: 'Khitish Chakravarti' },
    { ID: 187, FID: 115, name: 'Bandana Majumdar', aka: 'Mantu', gender: 'F' },
    { ID: 188, FID: -1, gender: 'M', name: 'Jiten Chakravarti' },
    { ID: 189, FID: 115, name: 'Archana Majumdar', gender: 'F', aka: 'Kali' },
    { ID: 190, FID: -1, gender: 'M', name: 'Ama Kumar Phani' },
    { ID: 191, FID: 129, name: 'Daughter', aka: 'Khuku', gender: 'F' },
    { ID: 192, FID: -1, gender: 'M', name: 'Husband' },
    { ID: 193, FID: 129, name: 'Daughter', aka: 'Bulbuli', gender: 'F' },
    { ID: 194, FID: -1, gender: 'M', name: 'Jayant Lahiri' },
    { ID: 195, FID: 129, name: 'Mohan Kumar Phani', dob: '2-Oct-1950' },
    { ID: 196, FID: -1, name: 'Lipika Sen', aka: 'Chumki', gender: 'F', dob: '5-Feb-1950' },
    { ID: 197, FID: 16, name: 'Hemangini Majumdar', gender: 'F' },
    { ID: 198, FID: -1, gender: 'M', name: 'Kumudnath Bhaduri' },
    { ID: 199, FID: 12, name: 'Daughter', gender: 'F' },
    { ID: 200, FID: 1, gender: 'M', name: 'Shambhu Roy Talukdar' },
    { ID: 201, FID: -1, name: 'Wife', gender: 'F' },
    { ID: 202, FID: 135, gender: 'M', name: 'To Do' },
    { ID: 203, FID: 1, gender: 'M', name: 'Rudra Roy Majumdar' },
]																										